# .circleci/config.yml
version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.19

jobs:
  build-android:
    executor: node-executor
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Install EAS CLI
          command: npm install -g eas-cli

      - run:
          name: Authenticate with Expo
          command: eas whoami || eas login --token $EXPO_TOKEN

      - run:
          name: Build Android app
          command: eas build --platform android --non-interactive

workflows:
  version: 2
  build:
    jobs:
      - build-android
