version: 2.1

jobs:
  node:
    working_directory: ~/app-deploy
    docker:
      - image: cimg/node:18.20.4

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-yarn-dependencies-{{ checksum "yarn.lock" }}
            - v1-yarn-dependencies-

      - run:
          name: Install Yarn Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v1-yarn-dependencies-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: ~/app-deploy
          paths:
            - node_modules
            - .

  android-build-and-test:
    working_directory: ~/app-deploy/android
    docker:
      - image: cimg/android:2024.07.1-node
    resource_class: large

    steps:
      - checkout:
          path: ~/app-deploy

      - attach_workspace:
          at: ~/app-deploy

      - restore_cache:
          keys:
            - v1-android-dependencies-{{ checksum "build.gradle" }}
            - v1-android-dependencies-

      - run:
          name: Install Ninja and CMake (for native builds)
          command: |
            sudo apt-get update
            sudo apt-get install -y ninja-build cmake

      - run:
          name: Fix Ruby permissions
          command: |
            sudo chown -R circleci:circleci /var/lib/gems /usr/local/bin && \
            sudo chmod -R 755 /var/lib/gems /usr/local/bin

      - run:
          name: Install Fastlane Dependencies
          command: bundle install

      - run:
          name: Run Fastlane Android Release
          no_output_timeout: 20m
          command: |
            mkdir -p release
            bundle exec fastlane android release
            mv app/build/outputs/apk/release/app-release.apk release/app-release-$(echo $CIRCLE_BUILD_NUM).apk
            mv app/build/outputs/bundle/release/app-release.aab release/app-release-$(echo $CIRCLE_BUILD_NUM).aab

      - store_artifacts:
          path: release

      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: v1-android-dependencies-{{ checksum "build.gradle" }}

workflows:
  build:
    jobs:
      - node
      - android-build-and-test:
          requires:
            - node
