version: 2.1

executors:
  android-eas:
    docker:
      - image: cimg/node:18.19
    working_directory: ~/project

jobs:
  build-apk:
    executor: android-eas
    environment:
      ANDROID_SDK_ROOT: /opt/android-sdk
      ANDROID_HOME: /opt/android-sdk
    steps:
      - checkout

      - run:
          name: Instalar Android SDK
          command: |
            sudo mkdir -p /opt/android-sdk/cmdline-tools
            curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o cmdline-tools.zip
            unzip -q cmdline-tools.zip -d /tmp/cmdline-tools
            sudo mv /tmp/cmdline-tools/cmdline-tools /opt/android-sdk/cmdline-tools/latest
            export PATH=$PATH:/opt/android-sdk/cmdline-tools/latest/bin
            export PATH=$PATH:/opt/android-sdk/platform-tools

            yes | sdkmanager --sdk_root=${ANDROID_SDK_ROOT} --licenses || true
            sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - run:
          name: Instalar EAS CLI
          command: npm install -g eas-cli

      - run:
          name: Build APK com EAS (local)
          command: |
            export PATH=$PATH:/opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/platform-tools
            eas build --platform android --profile preview --local --output=./apk

      - store_artifacts:
          path: apk
          destination: apk

workflows:
  build-and-export:
    jobs:
      - build-apk
