version: 2.1

executors:
  android-eas:
    docker:
      - image: cimg/node:18.19
    working_directory: ~/project

jobs:
  build-apk:
    executor: android-eas
    steps:
      - checkout

      - run:
          name: Instala dependências
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk
            curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o cmdline-tools.zip
            unzip cmdline-tools.zip
            mkdir -p $HOME/android-sdk/cmdline-tools
            mv cmdline-tools $HOME/android-sdk/cmdline-tools/latest
            export ANDROID_HOME=$HOME/android-sdk
            export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator
            yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
            sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - run:
          name: Instala EAS CLI
          command: npm install -g eas-cli

      - run:
          name: Faz build do APK localmente
          command: |
            export ANDROID_HOME=$HOME/android-sdk
            eas build --platform android --profile local --local

      - persist_to_workspace:
          root: .
          paths:
            - dist

      - store_artifacts:
          path: dist
          destination: apk
