version: 2.1

executors:
  android-executor:
    docker:
      - image: cimg/android:2023.10
    working_directory: ~/project

jobs:
  build-android:
    executor: android-executor
    steps:
      - checkout

      - run:
          name: Install Node.js via nvm
          command: |
            export NVM_DIR="$HOME/.nvm"
            source /usr/local/share/nvm/nvm.sh
            nvm install 18
            nvm use 18
            node -v
            npm -v

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install Node dependencies
          command: |
            export NVM_DIR="$HOME/.nvm"
            source /usr/local/share/nvm/nvm.sh
            nvm use 18
            npm ci

      - run:
          name: Install Java dependencies
          command: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Build Android Release APK
          command: cd android && ./gradlew assembleRelease

      - store_artifacts:
          path: android/app/build/outputs/apk/release/app-release.apk
          destination: release-apk

workflows:
  version: 2
  build:
    jobs:
      - build-android
